# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 180f8f2663ed5b73dfa9e4ef4e1aa1f77d9d890754ae42e29bf270576cf6c2358335f14051da17ec25df1e6000d50785eec8a359aa18586dc102e5d54e42af6f

test:
  secret_key_base: 339e1bd74d70c2504ad2db85e31a5fac610c784c55b4521fbcae51a02125996a96df37da6c268a2da609d1678cf16a59530e40b558877f2d6d0be1272c02c499

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
